const Student=[
    {
        "id":0,
        "Name":"Akshay",
        "Age":"23",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":1,
        "Name":"Aksha",
        "Age":"25",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":2,
        "Name":"Ashay",
        "Age":"22",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":3,
        "Name":"Aksay",
        "Age":"21",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":4,
        "Name":"Ashay",
        "Age":"23",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":5,
        "Name":"Akhay",
        "Age":"29",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":6,
        "Name":"Aksh",
        "Age":"23",
        "Course":"MERN",
        "Batch":"October"
    },
]
export default Student